version: 0.0
os: linux
files:
  - source: /app.zip
    destination: /var/www/myapp
hooks:
  BeforeInstall:
    - location: scripts/create_directory.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
