version: 0.0
os: linux
files:
  - source: /app.zip
    destination: /var/www/myapp
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/install_gunicorn.sh
      timeout: 300
      runas: root
    - location: scripts/fix_permissions.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/create_gunicorn_service.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
